=begin
#Payments-VPN

#Esta API fornece os serviços de pagamento do Banco do Brasil.

OpenAPI spec version: 3.5

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.24
=end

require 'spec_helper'
require 'json'

# Unit tests for BancoBrasilPayments::BankSlipsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'BankSlipsApi' do
  before do
    # run before each test
    @instance = BancoBrasilPayments::BankSlipsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BankSlipsApi' do
    it 'should create an instance of BankSlipsApi' do
      expect(@instance).to be_instance_of(BancoBrasilPayments::BankSlipsApi)
    end
  end

  # unit tests for consulta_pagamento_boleto
  # Barcode Payment Slip Details
  # Detalha um boleto de pagamento.
  # @param id Código identificador do pagamento.
  # @param gw_dev_app_key Chave de acesso do aplicativo do desenvolvedor. Esta chave é única e obtida no Portal “BB for Developers” e usada para identificar as requisições da aplicação do desenvolvedor.  Example: 0021239456d80136bebf005056891bed
  # @param authorization É um “token” de acesso fornecido pelo OAuth 2.0.  Example: Bearer [ACCESS_TOKEN]
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :agencia Código da agência para débito. Não é necessário quando a solicitação é acessada pelo código de autorização no fluxo do OAuth.
  # @option opts [Integer] :conta Conta corrente de débito. Não é necessário quando a solicitação é acessada pelo código de autorização no fluxo do OAuth. 
  # @option opts [String] :digito_conta Dígito do verificador da conta corrente para débito. Não é necessário quando a solicitação é acessada pelo código de autorização no fluxo do OAuth. 
  # @return [InlineResponse2003]
  describe 'consulta_pagamento_boleto test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for enviar_pagamento_boletos_lote
  # Batch Payment of Bank Slips
  # solicitar pagamento em lote de Boletos
  # @param body Objeto de requisição do recurso de pagamento em lote de Boletos.
  # @param authorization É um “token” de acesso fornecido pelo OAuth 2.0.  Example: Bearer [ACCESS_TOKEN]
  # @param gw_dev_app_key Chave de acesso do aplicativo do desenvolvedor. Esta chave é única e obtida no Portal “BB for Developers” e usada para identificar as requisições da aplicação do desenvolvedor.  Example: 0021239456d80136bebf005056891bed
  # @param [Hash] opts the optional parameters
  # @return [RootTypeForBankSlipsBatchPaymentResponseObject]
  describe 'enviar_pagamento_boletos_lote test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for sondagem_pagamento_boleto
  # Checks the payment of Bank Slips made in the Request Payment feature
  # Consulta o pagamento de Boletos realizado no recurso de Solicitação de Pagamento. Recurso utilizado quando a empresa não recebeu a confirmação da Solicitação de Pagamento do Boleto, ou quando precisar recuperar a resposta original ou quando quer confirmar que o número requestID já foi utilizado.
  # @param id Numero controlado pelo cliente para identificar cada acionamento da API e os lançamentos de cada chamada. Não precisa ser sequencial. De uso único.
  # @param [Hash] opts the optional parameters
  # @return [RootTypeForBankSlipsBatchPaymentResponseObject]
  describe 'sondagem_pagamento_boleto test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
