=begin
#Payments-VPN

#Esta API fornece os serviços de pagamento do Banco do Brasil.

OpenAPI spec version: 3.5

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.24
=end

require 'spec_helper'
require 'json'

# Unit tests for BancoBrasilPayments::CancelApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CancelApi' do
  before do
    # run before each test
    @instance = BancoBrasilPayments::CancelApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CancelApi' do
    it 'should create an instance of CancelApi' do
      expect(@instance).to be_instance_of(BancoBrasilPayments::CancelApi)
    end
  end

  # unit tests for cancelamento_transferencia_lote
  # Cancels a request for transfers in batch
  # Cancela, em lote, solicitações de transferências e de pagamentos boletos e guias, requisitadas através dos recursos: /batch-transfers (POST), /barcode-collection-forms (POST), /payments-vpn/v2/batch-slips (POST).
  # @param body Objeto de Requisição do recurso Batch Transfers Cancel
  # @param authorization É um “token” de acesso fornecido pelo OAuth 2.0.  Example: Bearer [ACCESS_TOKEN]
  # @param gw_dev_app_key Chave de acesso do aplicativo do desenvolvedor. Esta chave é única e obtida no Portal “BB for Developers” e usada para identificar as requisições da aplicação do desenvolvedor.  Example: 0021239456d80136bebf005056891bed
  # @param [Hash] opts the optional parameters
  # @return [RootTypeForBatchTransfersCancelResponseObject]
  describe 'cancelamento_transferencia_lote test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
