=begin
#Payments-VPN

#Esta API fornece os serviços de pagamento do Banco do Brasil.

OpenAPI spec version: 3.5

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.24
=end

require 'spec_helper'
require 'json'

# Unit tests for BancoBrasilPayments::CollectionFormsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CollectionFormsApi' do
  before do
    # run before each test
    @instance = BancoBrasilPayments::CollectionFormsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CollectionFormsApi' do
    it 'should create an instance of CollectionFormsApi' do
      expect(@instance).to be_instance_of(BancoBrasilPayments::CollectionFormsApi)
    end
  end

  # unit tests for consulta_pagamento_guia_lote
  # Consulta Pagamentos em Lote de Guias com Código de Barra
  # A partir de um código identificador de pagamento de uma Guia com Código de Barra, retorna os detalhes do pagamento desta, como estado do pagamento, data do pagamento, forma do pagamento, valor, descrição, código de devolução, entre outros.
  # @param id Numero controlado pelo cliente para identificar cada acionamento da API e os lançamentos de cada chamada. Não precisa ser sequencial. De uso único.
  # @param authorization É o valor do token de acesso fornecido pelo OAuth. Exemplo: Bearer &lt;acess_token&gt;
  # @param gw_dev_app_key É a chave de acesso do aplicativo do desenvolvedor obtida no Portal do Desenvolvedor. Essa chave será usada para identificação do aplicativo.
  # @param [Hash] opts the optional parameters
  # @option opts [Float] :agencia Número da agência da conta corrente de débito do valor total de cada requisição. Quando utilizado o fluxo Client Credentials, esse campo é informado pelo cliente. Quando utilizado o fluxo Authorization Code, essa informação é do token.
  # @option opts [Float] :conta_corrente Número da conta corrente de débito do valor total de cada requisição. Quando utilizado o fluxo Client Credentials, esse campo é informado pelo cliente. Quando utilizado o fluxo Authorization Code, essa informação é do token.
  # @option opts [String] :digito_verificador Dígito verificador da conta corrente de débito do valor total de cada requisição. Quando utilizado o fluxo Client Credentials, esse campo é informado pelo cliente. Quando utilizado o fluxo Authorization Code, essa informação é do token.
  # @return [BarcodeCollectionFormsIDResponseObject]
  describe 'consulta_pagamento_guia_lote test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for envia_pagamento_guias_lote
  # Barcode Collection Forms Payment
  # Solicitar pagamento em lote de Guias de Recolhimento com código de barras.
  # @param body Objeto de requisição do recurso de pagamento em lote de Guias com Código de Barras.
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse2011]
  describe 'envia_pagamento_guias_lote test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for sondagem_pagamento_guia_lote
  # Barcode Collection Forms Payment Check
  # Consultar a resposta de uma solicitação de pagamento em lote de guias de recolhimento com código de barras.
  # @param id Identificação da solicitação de pagamento. É um número único, não sequencial, cujo valor vai de 1 a 999999999.
  # @param gw_dev_app_key Chave de acesso do aplicativo do desenvolvedor. Esta chave é única e obtida no Portal “BB for Developers” e usada para identificar as requisições da aplicação do desenvolvedor.  Example: 0021239456d80136bebf005056891bed
  # @param authorization É um “token” de acesso fornecido pelo OAuth 2.0.  Example: Bearer [ACCESS_TOKEN]
  # @param debit_branch_office Código da agência para débito. Não é necessário quando a solicitação é acessada pelo código de autorização no fluxo do OAuth.
  # @param debit_current_account Conta corrente de débito. Não é necessário quando a solicitação é acessada pelo código de autorização no fluxo do OAuth.
  # @param check_digits_debit_current_account Dígito do verificador da conta corrente para débito. Não é necessário quando a solicitação é acessada pelo código de autorização no fluxo do OAuth.
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse2011]
  describe 'sondagem_pagamento_guia_lote test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
