=begin
#Payments-VPN

#Esta API fornece os serviços de pagamento do Banco do Brasil.

OpenAPI spec version: 3.5

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.24
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for BancoBrasilPayments::BarcodeCollectionFormsIDResponseObject
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'BarcodeCollectionFormsIDResponseObject' do
  before do
    # run before each test
    @instance = BancoBrasilPayments::BarcodeCollectionFormsIDResponseObject.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BarcodeCollectionFormsIDResponseObject' do
    it 'should create an instance of BarcodeCollectionFormsIDResponseObject' do
      expect(@instance).to be_instance_of(BancoBrasilPayments::BarcodeCollectionFormsIDResponseObject)
    end
  end
end
