=begin
#Payments-VPN

#Esta API fornece os serviços de pagamento do Banco do Brasil.

OpenAPI spec version: 3.5

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.24
=end

module BancoBrasilPayments
  class TransfersApi
    include BatchPayments # pagamentos-lote/v1
    include BatchPaymentsBeta # payments-vpn/v3

    attr_accessor :api_client, :gw_app_key

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
      @gw_app_key = @api_client.config.gw_app_key
    end
  end
end
